// © 2026 RadianceNoMore (Sonoro-Score, MIT).
// Fixture-corpus runner: 1080p panel PNG + verified/unverified sidecar per sample.
// Unverified fixtures pin current output exactly (any drift fails → re-baseline).
// Verified fixtures score toward the 0.95 corpus floor. See the project notes §6.

using System.Text.Json;
using System.Drawing;
using SonoroScore.Scanner;
using Xunit;
using Xunit.Abstractions;

namespace SonoroScore.Scanner.Tests;

public sealed class EchoFixtureTests
{
    private const double VerifiedAccuracyFloor = 0.95;

    private readonly ITestOutputHelper _log;

    public EchoFixtureTests(ITestOutputHelper log)
    {
        _log = log;
    }

    [Fact]
    [Trait("gate", "verified")]
    public async Task FixtureCorpus_RulesHold()
    {
        string dir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
            "fixtures", "echoes", "english-1080p");
        Assert.True(Directory.Exists(dir), $"Fixture dir missing: {dir}");
        string[] sidecars = Directory.GetFiles(dir, "*.json").OrderBy(f => f).ToArray();
        Assert.NotEmpty(sidecars);

        var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        var fixtures = sidecars
            .Select(f => JsonSerializer.Deserialize<EchoFixture>(File.ReadAllText(f), opts)!)
            .ToList();

        // A-01: match against the REAL committed catalog snapshot. Building the
        // catalog from the fixtures' own answers made name bugs invisible (F-02).
        string catalogPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
            "fixtures", "catalog", "echo_catalog.json");
        Assert.True(File.Exists(catalogPath), $"Catalog snapshot missing: {catalogPath}");
        EchoCatalogEntry[] catalog = await GameDatabase.LoadFromFileAsync(catalogPath);
        _log.WriteLine($"Catalog loaded: {catalog.Length} entries ({GameDatabase.DataVersion})");

        var recognizer = new EchoRecognizer(catalog);
        int verifiedMatched = 0, verifiedTotal = 0;
        var failures = new List<string>();   // verified fixtures only (A-03)
        var drifts = new List<string>();     // unverified fixtures: report-only (A-03)
        var reportEntries = new List<AccuracyReport.FieldEntry>();   // A-07

        foreach (var fixture in fixtures)
        {
            string png = Path.Combine(dir, fixture.SourceImage);
            Assert.True(File.Exists(png), $"Fixture image missing: {png}");
            Bitmap panel = new Bitmap(png); // ownership transfers to RecognizePanelAsync
            EchoScanResult scan = await recognizer.RecognizePanelAsync(panel, fixture.SourceImage);
            EchoAccuracyReport acc = EchoAccuracy.Score(scan, fixture);
            reportEntries.AddRange(AccuracyReport.Entries(fixture, scan, acc));

            string? name = scan.EchoName?.Value as string;
            _log.WriteLine($"{fixture.SourceImage} verified={fixture.Verified} " +
                           $"rate={acc.Rate:P1} name={name} " +
                           $"miss=[{string.Join(",", acc.Fields.Where(f => !f.Match).Select(f => f.Field))}]");

            if (!fixture.Verified)
            {
                // A-03: an unverified sidecar only pins the pipeline's own output, so
                // drift is REPORT-ONLY - logged loudly, never asserted (a test that
                // pins a bug is a bug).
                if (acc.Rate < 1.0)
                    drifts.Add($"{fixture.SourceImage}: unverified snapshot drifted ({acc.Rate:P1}): " +
                               string.Join("; ", acc.Fields.Where(f => !f.Match).Select(f => $"{f.Field} exp={f.Expected} got={f.Actual}")));
            }
            else
            {
                // Verified truth: fail per field, naming expected vs actual.
                foreach (var f in acc.Fields.Where(f => !f.Match))
                    failures.Add($"{fixture.SourceImage}: [{f.Field}] expected '{f.Expected}' got '{f.Actual}'");
                verifiedMatched += acc.Matched;
                verifiedTotal += acc.Total;
            }
        }

        if (drifts.Count > 0)
            _log.WriteLine("Unverified fixture drift (report-only, A-03):\n  " + string.Join("\n  ", drifts));

        // A-07: the same accuracy_report.json the CLI writes with --truth.
        string reportPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "accuracy_report.json");
        File.WriteAllText(reportPath, AccuracyReport.ToJson(reportEntries, "generated by Scanner.Tests fixture corpus"));
        _log.WriteLine($"accuracy report: {reportPath}");

        double verifiedRate = verifiedTotal == 0 ? double.NaN : (double)verifiedMatched / verifiedTotal;
        _log.WriteLine($"verified fields: {verifiedMatched}/{verifiedTotal} " +
                       (double.IsNaN(verifiedRate) ? "(no verified fixtures yet)" : $"= {verifiedRate:P1} (floor {VerifiedAccuracyFloor:P0})"));

        Assert.True(failures.Count == 0,
            "Verified fixture failures:\n" + string.Join("\n", failures));
        if (verifiedTotal > 0)
            Assert.True(verifiedRate >= VerifiedAccuracyFloor,
                $"Verified corpus accuracy {verifiedRate:P1} below floor {VerifiedAccuracyFloor:P0}.");
    }

    [Fact]
    public async Task Catalog_ContainsAllFixtureNames()
    {
        string dir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
            "fixtures", "echoes", "english-1080p");
        string catalogPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
            "fixtures", "catalog", "echo_catalog.json");

        var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        var fixtureNames = Directory.GetFiles(dir, "*.json")
            .OrderBy(f => f)
            .Select(f => JsonSerializer.Deserialize<EchoFixture>(File.ReadAllText(f), opts)!.Name)
            .Where(n => !string.IsNullOrEmpty(n))
            .Distinct(StringComparer.Ordinal)
            .ToList();

        EchoCatalogEntry[] catalog = await GameDatabase.LoadFromFileAsync(catalogPath);
        var catalogNames = catalog.Select(c => c.Name).ToHashSet(StringComparer.Ordinal);

        var missing = fixtureNames.Where(n => !catalogNames.Contains(n!)).ToList();
        Assert.True(missing.Count == 0,
            "Fixture names missing verbatim from the catalog snapshot: " + string.Join(", ", missing));
    }

    [Fact]
    public async Task ReviewFlags_OnlyCountRowsThatFailedToResolve()
    {
        // F-43: NoteRollState handled Corrected/Ambiguous and let EXACT fall through
        // to the default branch, so every exact (perfectly legal) roll was flagged
        // "NotARoll: value is not a legal roll". Nothing consumed Flags, so no test
        // noticed. Invariant for the review output: the roll flags count exactly the
        // substat rows that did NOT resolve to a value.
        string dir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
            "fixtures", "echoes", "english-1080p");
        string catalogPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
            "fixtures", "catalog", "echo_catalog.json");
        EchoCatalogEntry[] catalog = await GameDatabase.LoadFromFileAsync(catalogPath);
        var recognizer = new EchoRecognizer(catalog);

        var violations = new List<string>();
        int exactRows = 0;
        foreach (string png in Directory.GetFiles(dir, "*.png").OrderBy(f => f))
        {
            Bitmap panel = new Bitmap(png);
            EchoScanResult scan = await recognizer.RecognizePanelAsync(panel, Path.GetFileName(png));
            int unresolved = scan.Substats.Count(s => s.SnappedValue == null);
            int flagged = scan.Flags.Count(f => f is "NotARoll" or "AmbiguousRoll");
            exactRows += scan.Substats.Count(s => s.SnappedValue != null);
            if (flagged != unresolved)
                violations.Add($"{Path.GetFileName(png)}: {flagged} roll flag(s) vs {unresolved} unresolved row(s)");
        }

        _log.WriteLine($"substat rows resolved exactly: {exactRows}");
        Assert.True(violations.Count == 0,
            "Roll flags do not match unresolved rows:\n" + string.Join("\n", violations));
    }
}
